#!/bin/bash

case "$1" in
	shutdown)
		poweroff
		;;
	reboot)
		reboot
		;;
	logout)
		loginctl list-sessions | grep tty1 | cut -f7 -d' '
		;;
	suspend)
		systemctl suspend
		;;
	switch-user)
		dm-tool switch-to-greeter
		;;
	lock)
		loginctl lock-session
		;;
	*)
		echo "syscontrol: missing or invalid argument"
		echo "Available commands: shutdown, reboot, logout, suspend, switch-user, lock"
		exit 1
esac

exit 0
