[editor]
line-number = "relative"
cursorline = true
insert-final-newline = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.lsp]
display-messages = true
display-progress-messages = true

[editor.indent-guides]
render = true
skip_levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
w = 'move_next_sub_word_start'
b = 'move_prev_sub_word_start'
e = 'move_next_sub_word_end'

[keys.select]
w = 'extend_next_sub_word_start'
b = 'extend_prev_sub_word_start'
e = 'extend_next_sub_word_end'

[keys.normal.Z]
Z = ":wq"
Q = ":q!"

[keys.normal.space]
q = ":buffer-close"
t = ":buffer-next"
T = ":buffer-previous"

[keys.insert]
j = { k = "normal_mode" }
