[Settings]
# manual
gtk-application-prefer-dark-theme=true
gtk-font-name=Sans, 10
gtk-icon-theme-name=Papirus-Dark
gtk-theme-name=Flat-Remix-GTK-Blue-Dark
gtk-cursor-theme-name=breeze_cursors
gtk-cursor-theme-size=21

# automatically written settings transfered verbatim
gtk-sound-theme-name=ocean
gtk-primary-button-warps-slider=true
gtk-enable-animations=true
gtk-decoration-layout=icon:minimize,maximize,close
gtk-cursor-blink=true
gtk-cursor-blink-time=1000
