# Used by the shell to check if environment.d variables have already been applied
# (e.g. if the shell was spawned by systemd).
# If not, then the shell can parse environment.d by itself
ENVD_APPLIED=1
