PATH="$HOME/.local/bin:$HOME/.local/opt/android/cmdline-tools/latest/bin:$HOME/.cargo/bin:$HOME/.deno/bin:$HOME/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:$PATH"
XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:$HOME/.nix-profile/share:$XDG_DATA_DIRS"

# android SDK (also cmdline-tools in PATH)
ANDROID_HOME="$HOME/.local/opt/android"
ANDROID_NDK_HOME="$HOME/.local/opt/android/ndk-bundle"
