#!/bin/bash

if grep "^ID_LIKE=" /etc/os-release &>/dev/null; then
        OS=$(grep "^ID_LIKE" /etc/os-release | cut -d= -f2)
elif grep "^ID=" /etc/os-release &>/dev/null; then
        OS=$(grep "^ID" /etc/os-release | cut -d= -f2)
fi

if [ "$OS" = "arch" ]; then
	if ! updates_repo=$(checkupdates 2> /dev/null | wc -l); then
		updates_repo=0
	fi
	
	if ! updates_aur=$(yay -Qum 2>/dev/null | wc -l); then
		updates_aur=0
	fi
	
	updates=$(( "$updates_repo" + "$updates_aur" ))
fi

if (( "$updates" > 0 )); then
	echo "ﮮ $updates"
else
	echo
fi
